### ISSUE TITLE
Unsupported input formats. 

### ISSUE THREAD

**Issue by brucethemoose** [IFeelBloated/Vine#1]
What kind of input format does Dehalo need to actually work?

If I use my normal, 8 bit video input, or I convert it to 16 bits before running dehalo with "video = core.fmtc.bitdepth(video,bits=16,fulls=False,fulld=True)", it throws the exception "the sample type of src has to be single precision!".

If I use "video = core.fmtc.bitdepth(video,bits=32,fulls=False,fulld=True)" I get the exception "Only clips with integer samples and 8,, 16 bits per sample supported". 

One message says it only takes 32 bit input, the other says only 8 or 16... What gives?

This probably belongs in the Doom9 forums, but my old account disappeared and my 5 day registration period isn't over yet.

**Comment by IFeelBloated** [comment]
you need the latest version of vapoursynth

> r33:
> ...
> optimized minimum, maximum, median, deflate, inflate, convolution (1x3, 3x1 and 3x3) on x86 cpus
> added float support to minimum, maximum, median, deflate, inflate, convolution, prewitt, sobel, invert, limiter, binarize and levels functions, note that most of the arguments have been changed from int to float
> the whole project can now be compiled with clang-cl under windows
> ...
